# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C4uZFxlrxkFDsijxhF9_t9vnj-pGvWoQ
"""

# Tabela de substituição simples
tabela_cripto = {
    'A': 'Q', 'B': 'W', 'C': 'E', 'D': 'R', 'E': 'T',
    'F': 'Y', 'G': 'U', 'H': 'I', 'I': 'O', 'J': 'P',
    'K': 'A', 'L': 'S', 'M': 'D', 'N': 'F', 'O': 'G',
    'P': 'H', 'Q': 'J', 'R': 'K', 'S': 'L', 'T': 'Z',
    'U': 'X', 'V': 'C', 'W': 'V', 'X': 'B', 'Y': 'N',
    'Z': 'M'
}

# Invertendo a tabela para descriptografia
tabela_descripto = {v: k for k, v in tabela_cripto.items()}

def criptografar(texto):
    texto = texto.upper()
    resultado = ''
    for letra in texto:
        if letra in tabela_cripto:
            resultado += tabela_cripto[letra]
        else:
            resultado += letra  # mantém espaços e pontuação
    return resultado

def descriptografar(texto):
    texto = texto.upper()
    resultado = ''
    for letra in texto:
        if letra in tabela_descripto:
            resultado += tabela_descripto[letra]
        else:
            resultado += letra
    return resultado

# Exemplo de uso
mensagem = "kauan"
mensagem_criptografada = criptografar(mensagem)
mensagem_descriptografada = descriptografar(mensagem_criptografada)

print("Mensagem Original:", mensagem)
print("Criptografada:", mensagem_criptografada)
print("Descriptografada:", mensagem_descriptografada)



from google.colab import drive
drive.mount('/content/drive')